import Alert from "./Alert.jsx";
import Loader from "./Loader.jsx";
import HomeInfo from "./HomeInfo.jsx";
import CTA from "./CTA.jsx";
import Footer from "./Footer.jsx";
import GreenTree from "./Island/GreenTree.jsx";
import PinkHouse from "./Island/PinkHouse.jsx";
import YellowTree  from "./Island/YellowTree.jsx";
import BlueHouse from "./Island/BlueHouse.jsx";
import Island from "./Island/Island.jsx";
import RedTree from "./Island/RedTree.jsx";
import BlueTree from "./Island/BlueTree.jsx";
import RedHouse from "./Island/RedHouse.jsx";
import BlockCompetence from "./BlockCompetence.jsx";
import ProjectBlock from "./ProjectBlock.jsx";
export { Alert, Loader, HomeInfo, CTA, Footer, GreenTree, PinkHouse, YellowTree, BlueHouse, Island, RedTree, BlueTree, RedHouse, BlockCompetence, ProjectBlock};